sudo: required
dist: trusty
language: generic

addons:
  apt:
    packages:
      - texlive-full
      - latexmk
      - python-pygments
      - inkscape

before_install:
    - lsb_release -a
    - uname -a
    - printenv

install:
    - make minted

script:
    - make
