sudo: required
dist: focal
language: generic

addons:
  apt:
    packages:
      - texlive-full
      - python3-pygments
      - python-is-python3
      - inkscape

before_install:
    - lsb_release -a
    - uname -a
    - printenv

script:
    - make
