sudo: required
dist: trusty

before_install:
    - lsb_release -a
    - uname -a
    - printenv
    - sudo apt-get -qq update
    - sudo apt-get install -y texlive-full latexmk python-pygments

install:
    - make minted

script:
    - make
