sudo: required
dist: trusty

language: generic

before_install:
    - lsb_release -a
    - uname -a
    - printenv
    - sudo apt-get -qq update
    - sudo apt-get install -y texlive-full latexmk python-pygments inkscape

install:
    - make minted

script:
    - make
